# Generated by Django 3.0.3 on 2020-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmedia',
            old_name='post',
            new_name='postitem',
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='posts.PostMedia'),
        ),
    ]
